"""recreation

Revision ID: 43161d509c3f
Revises: 8c3837deff95
Create Date: 2024-07-10 00:34:53.370354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43161d509c3f'
down_revision: Union[str, None] = '8c3837deff95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('car_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_brand', sa.String(length=64), nullable=False),
    sa.Column('car_model', sa.String(length=64), nullable=False),
    sa.Column('rent_deposit', sa.Integer(), nullable=False),
    sa.Column('car_class', sa.String(length=32), nullable=False),
    sa.Column('drive_unit', sa.String(length=32), nullable=False),
    sa.Column('car_fuel', sa.String(length=32), nullable=False),
    sa.Column('car_year', sa.Integer(), nullable=False),
    sa.Column('engine_power', sa.Integer(), nullable=False),
    sa.Column('transmission', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('car_number', sa.String(length=64), nullable=False),
    sa.Column('car_photo', sa.String(length=256), nullable=False),
    sa.Column('car_status', sa.String(), nullable=False),
    sa.CheckConstraint("car_class in ('A', 'B', 'C', 'D', 'E', 'F', 'M', 'S', 'J', 'truck', 'van')"),
    sa.CheckConstraint("car_fuel in ('дизель', 'бензин', 'гибрид', 'электро', 'водород')"),
    sa.CheckConstraint("car_status in ('0', '1')"),
    sa.CheckConstraint("drive_unit in ('FWD', 'RWD', '4WD')"),
    sa.CheckConstraint("transmission in ('АКПП', 'МКПП', 'Вариатор', 'Робот')"),
    sa.CheckConstraint('car_year > 1970'),
    sa.CheckConstraint('rent_deposit > 0'),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('cars')
    # ### end Alembic commands ###
